import type { Metadata, Viewport } from "next";
import { Inter, DM_Serif_Display } from "next/font/google";
import { RouteProvider } from "@/providers/router-provider";
import { Theme } from "@/providers/theme";
import { QueryProvider } from "@/providers/query-provider";
import { cx } from "@/utils/cx";
import "@/styles/globals.css";
// Initialize background services automatically
import "@/lib/startup";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

const dmSerifDisplay = DM_Serif_Display({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-dm-serif-display",
    weight: "400",
});

export const metadata: Metadata = {
    title: "Starter kit — Untitled UI",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#7f56d9",
    colorScheme: "light dark",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cx(inter.variable, dmSerifDisplay.variable, "bg-primary antialiased")}>
                <RouteProvider>
                    <QueryProvider>
                        <Theme>{children}</Theme>
                    </QueryProvider>
                </RouteProvider>
            </body>
        </html>
    );
}
